import { fold } from './text';

/**
 * Hand-written, neutral background on institutions and terms that recur in
 * German and European news. Every entry is a stable, checkable fact about what
 * something *is* — never a characterisation of a current event.
 *
 * This is the honest half of "why it matters": a student meeting "Sondervermögen"
 * or "Bundesverfassungsgericht" for the first time gets a real explanation,
 * generated by nobody and requiring no caveat.
 */
export interface GlossaryEntry {
  id: string;
  /** Surface forms that trigger the entry, folded before matching. */
  match: string[];
  term: { de: string; en: string };
  body: { de: string; en: string };
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    id: 'bundestag',
    match: ['bundestag'],
    term: { de: 'Bundestag', en: 'Bundestag' },
    body: {
      de: 'Das gewählte Parlament des Bundes. Beschließt Gesetze, entscheidet über den Haushalt, wählt den Bundeskanzler und kontrolliert die Regierung.',
      en: 'Germany’s elected federal parliament. It passes laws, decides the budget, elects the chancellor and holds the government to account.',
    },
  },
  {
    id: 'bundesrat',
    match: ['bundesrat'],
    term: { de: 'Bundesrat', en: 'Bundesrat' },
    body: {
      de: 'Vertretung der 16 Bundesländer auf Bundesebene. Viele Gesetze brauchen seine Zustimmung, weshalb Mehrheiten dort eigene Verhandlungen erfordern.',
      en: 'The chamber representing Germany’s 16 states. Many federal laws need its consent, so a government can hold a Bundestag majority and still have to negotiate here.',
    },
  },
  {
    id: 'bundesverfassungsgericht',
    match: ['bundesverfassungsgericht', 'verfassungsgericht', 'karlsruhe'],
    term: { de: 'Bundesverfassungsgericht', en: 'Federal Constitutional Court' },
    body: {
      de: 'Höchstes deutsches Gericht in Verfassungsfragen, mit Sitz in Karlsruhe. Kann Gesetze für nichtig erklären; seine Entscheidungen binden alle staatlichen Organe.',
      en: 'Germany’s highest court for constitutional questions, seated in Karlsruhe. It can strike down laws outright, and its rulings bind every arm of the state.',
    },
  },
  {
    id: 'Sondervermögen',
    match: ['Sondervermögen'],
    term: { de: 'Sondervermögen', en: 'Sondervermögen (special fund)' },
    body: {
      de: 'Ein vom regulären Haushalt getrennter Topf, meist kreditfinanziert. Er ermöglicht Ausgaben, die sonst an der Schuldenbremse scheitern würden — und ist genau deshalb politisch umstritten.',
      en: 'A pot of money held outside the regular federal budget, usually debt-financed. It allows spending that the debt brake would otherwise block, which is exactly why it is politically contested.',
    },
  },
  {
    id: 'schuldenbremse',
    match: ['schuldenbremse', 'debt brake'],
    term: { de: 'Schuldenbremse', en: 'Debt brake' },
    body: {
      de: 'Im Grundgesetz verankerte Regel, die die jährliche Netto-Neuverschuldung des Bundes eng begrenzt. Ausnahmen sind nur in Notlagen möglich, die der Bundestag feststellen muss.',
      en: 'A rule written into Germany’s constitution that tightly caps new federal borrowing each year. Exceptions require the Bundestag to formally declare an emergency.',
    },
  },
  {
    id: 'koalition',
    match: ['koalition', 'koalitionsvertrag', 'coalition'],
    term: { de: 'Koalition', en: 'Coalition' },
    body: {
      de: 'Regierungsbündnis mehrerer Parteien, das nötig ist, weil im deutschen Verhältniswahlrecht selten eine Partei allein eine Mehrheit erreicht. Grundlage ist ein ausgehandelter Koalitionsvertrag.',
      en: 'An alliance of parties forming a government, needed because Germany’s proportional system rarely gives one party a majority. It runs on a negotiated coalition agreement.',
    },
  },
  {
    id: 'ezb',
    match: ['ecb', 'ezb', 'zentralbank'],
    term: { de: 'Europäische Zentralbank', en: 'European Central Bank' },
    body: {
      de: 'Setzt die Geldpolitik für die Länder der Eurozone. Ihr Hauptziel ist Preisstabilität, angestrebt werden rund zwei Prozent Inflation; ihr wichtigstes Werkzeug ist der Leitzins.',
      en: 'Sets monetary policy for the euro area. Its primary mandate is price stability, targeting inflation of around two percent, and its main lever is the key interest rate.',
    },
  },
  {
    id: 'leitzins',
    match: ['interestrate', 'leitzins', 'leitzinsen'],
    term: { de: 'Leitzins', en: 'Key interest rate' },
    body: {
      de: 'Der Zinssatz, zu dem sich Geschäftsbanken bei der Zentralbank Geld leihen. Er wirkt sich auf Kredite, Sparzinsen und Immobilienfinanzierungen aus — und wird genutzt, um Inflation zu dämpfen.',
      en: 'The rate at which commercial banks borrow from the central bank. It feeds through to loans, savings and mortgages, and is the standard tool for cooling inflation.',
    },
  },
  {
    id: 'inflation',
    match: ['inflation'],
    term: { de: 'Inflation', en: 'Inflation' },
    body: {
      de: 'Der allgemeine Anstieg des Preisniveaus über die Zeit. Sinkende Inflation bedeutet, dass die Preise langsamer steigen — nicht, dass sie fallen.',
      en: 'The general rise in prices over time. Falling inflation means prices are rising more slowly, not that they are coming down.',
    },
  },
  {
    id: 'rezession',
    match: ['recession'],
    term: { de: 'Rezession', en: 'Recession' },
    body: {
      de: 'Ein längerer Rückgang der Wirtschaftsleistung. Häufig verwendete Faustregel: zwei aufeinanderfolgende Quartale mit schrumpfendem Bruttoinlandsprodukt.',
      en: 'A sustained decline in economic output. The common rule of thumb is two consecutive quarters of shrinking GDP.',
    },
  },
  {
    id: 'eu',
    match: ['eu'],
    term: { de: 'Europäische Union', en: 'European Union' },
    body: {
      de: 'Staatenverbund von 27 Ländern mit gemeinsamem Binnenmarkt. Die Kommission schlägt Gesetze vor, Parlament und Rat der Mitgliedstaaten beschließen sie gemeinsam.',
      en: 'A union of 27 states with a shared single market. The Commission proposes legislation; the Parliament and the member states’ Council pass it together.',
    },
  },
  {
    id: 'nato',
    match: ['nato'],
    term: { de: 'NATO', en: 'NATO' },
    body: {
      de: 'Militärbündnis aus Nordamerika und Europa. Kern ist Artikel 5: Ein bewaffneter Angriff auf ein Mitglied gilt als Angriff auf alle.',
      en: 'A military alliance spanning North America and Europe. Its core is Article 5: an armed attack on one member counts as an attack on all.',
    },
  },
  {
    id: 'un',
    match: ['un'],
    term: { de: 'Vereinte Nationen', en: 'United Nations' },
    body: {
      de: 'Weltweite Organisation mit 193 Mitgliedstaaten. In der Generalversammlung hat jedes Land eine Stimme; bindende Beschlüsse fasst nur der Sicherheitsrat, in dem fünf Staaten ein Veto haben.',
      en: 'A global body of 193 member states. Every country has one vote in the General Assembly, but only the Security Council can pass binding resolutions, and five states there hold a veto.',
    },
  },
  {
    id: 'sanctions',
    match: ['sanctions'],
    term: { de: 'Sanktionen', en: 'Sanctions' },
    body: {
      de: 'Wirtschaftliche oder politische Zwangsmaßnahmen gegen Staaten, Unternehmen oder Einzelpersonen — etwa eingefrorene Konten, Handelsverbote oder Einreisesperren.',
      en: 'Economic or political measures imposed on states, companies or individuals — frozen assets, trade bans or travel restrictions.',
    },
  },
  {
    id: 'ceasefire',
    match: ['ceasefire'],
    term: { de: 'Waffenruhe', en: 'Ceasefire' },
    body: {
      de: 'Vereinbarte Einstellung der Kampfhandlungen. Sie beendet einen Krieg nicht rechtlich — dafür braucht es ein Friedensabkommen — und ist oft zeitlich oder örtlich begrenzt.',
      en: 'An agreed halt to fighting. It does not legally end a war — that needs a peace agreement — and is often limited in time or to a specific area.',
    },
  },
  {
    id: 'bundeswehr',
    match: ['bundeswehr'],
    term: { de: 'Bundeswehr', en: 'Bundeswehr' },
    body: {
      de: 'Die Streitkräfte Deutschlands. Auslandseinsätze brauchen in der Regel ein Mandat des Bundestages — eine Besonderheit, die Deutschland von den meisten Bündnispartnern unterscheidet.',
      en: 'Germany’s armed forces. Deployments abroad generally require a Bundestag mandate, a constraint that sets Germany apart from most of its allies.',
    },
  },
  {
    id: 'grundgesetz',
    match: ['grundgesetz'],
    term: { de: 'Grundgesetz', en: 'Basic Law' },
    body: {
      de: 'Die deutsche Verfassung von 1949. Änderungen brauchen Zweidrittelmehrheiten in Bundestag und Bundesrat; die Grundrechte der ersten Artikel sind unveränderlich.',
      en: 'Germany’s 1949 constitution. Amending it takes two-thirds majorities in both chambers, and the basic rights in its opening articles cannot be changed at all.',
    },
  },
  {
    id: 'landtagswahl',
    match: ['landtagswahl', 'landtag'],
    term: { de: 'Landtagswahl', en: 'State election' },
    body: {
      de: 'Wahl des Parlaments eines Bundeslandes. Länder entscheiden unter anderem über Bildung und Polizei — und die Ergebnisse gelten oft als Stimmungstest für die Bundespolitik.',
      en: 'An election for one German state’s parliament. States control areas such as education and policing, and results are widely read as a barometer for national politics.',
    },
  },
  {
    id: 'huerde',
    match: ['Fünfprozenthürde', 'sperrklausel'],
    term: { de: 'Fünf-Prozent-Hürde', en: 'Five percent threshold' },
    body: {
      de: 'Parteien ziehen nur ins Parlament ein, wenn sie mindestens fünf Prozent der Stimmen erreichen. Die Regel soll Zersplitterung verhindern.',
      en: 'A party only enters parliament if it wins at least five percent of the vote — a rule meant to prevent fragmentation.',
    },
  },
  {
    id: 'ai',
    match: ['ai'],
    term: { de: 'Künstliche Intelligenz', en: 'Artificial intelligence' },
    body: {
      de: 'Sammelbegriff für Systeme, die Muster aus Daten lernen, statt festen Regeln zu folgen. Die EU reguliert sie seit dem AI Act nach Risikoklassen.',
      en: 'An umbrella term for systems that learn patterns from data rather than following fixed rules. The EU’s AI Act regulates them by risk category.',
    },
  },
  {
    id: 'dsgvo',
    match: ['dsgvo', 'gdpr', 'Datenschutzgrundverordnung'],
    term: { de: 'DSGVO', en: 'GDPR' },
    body: {
      de: 'EU-weite Datenschutzregeln. Verarbeitung personenbezogener Daten braucht eine Rechtsgrundlage; Verstöße können mit bis zu vier Prozent des weltweiten Jahresumsatzes geahndet werden.',
      en: 'The EU’s data protection regime. Processing personal data needs a legal basis, and breaches can cost up to four percent of global annual turnover.',
    },
  },
  {
    id: 'climate',
    match: ['climate'],
    term: { de: 'Klimawandel', en: 'Climate change' },
    body: {
      de: 'Langfristige Veränderung des Klimas, überwiegend verursacht durch Treibhausgase aus fossilen Brennstoffen. Das Pariser Abkommen zielt darauf, die Erwärmung deutlich unter zwei Grad zu halten.',
      en: 'Long-term shifts in climate, driven mainly by greenhouse gases from fossil fuels. The Paris Agreement aims to hold warming well below two degrees.',
    },
  },
  {
    id: 'imf',
    match: ['imf'],
    term: { de: 'Internationaler Währungsfonds', en: 'International Monetary Fund' },
    body: {
      de: 'Organisation von 190 Staaten, die Ländern in Zahlungsschwierigkeiten Kredite gewährt — meist verbunden mit wirtschaftspolitischen Auflagen.',
      en: 'A 190-member body that lends to countries in financial distress, usually attaching conditions on economic policy.',
    },
  },
  {
    id: 'who',
    match: ['who'],
    term: { de: 'Weltgesundheitsorganisation', en: 'World Health Organization' },
    body: {
      de: 'UN-Sonderorganisation für globale Gesundheit. Koordiniert die Reaktion auf Epidemien und kann eine "gesundheitliche Notlage internationaler Tragweite" ausrufen.',
      en: 'The UN agency for global health. It coordinates epidemic response and can declare a public health emergency of international concern.',
    },
  },
  {
    id: 'tariffs',
    match: ['tariffs'],
    term: { de: 'Zölle', en: 'Tariffs' },
    body: {
      de: 'Abgaben auf importierte Waren. Sie verteuern ausländische Produkte, sollen heimische Anbieter schützen — und werden meist von den Importeuren und Verbrauchern getragen.',
      en: 'Taxes on imported goods. They make foreign products more expensive to shield domestic producers, and are mostly borne by importers and consumers.',
    },
  },
  {
    id: 'refugees',
    match: ['refugees', 'asyl'],
    term: { de: 'Asyl und Flucht', en: 'Asylum and refugees' },
    body: {
      de: 'Wer verfolgt wird, hat nach der Genfer Flüchtlingskonvention Anspruch auf Schutz. In der EU regelt das Dublin-System, welcher Staat für ein Asylverfahren zuständig ist.',
      en: 'People facing persecution have a right to protection under the Refugee Convention. Within the EU, the Dublin system decides which country handles a claim.',
    },
  },
];

/** Prebuilt lookup: folded surface form to entry. */
const BY_TOKEN = new Map<string, GlossaryEntry>();
for (const entry of GLOSSARY) {
  for (const form of entry.match) BY_TOKEN.set(fold(form), entry);
}

/**
 * Finds glossary entries relevant to a story. Matching runs over the clustering
 * tokens rather than raw text, so it benefits from the same alias bridge: a
 * German article saying "EZB" and an English one saying "ECB" both resolve here.
 */
export function findGlossary(tokens: string[], limit = 3): GlossaryEntry[] {
  const seen = new Set<string>();
  const out: GlossaryEntry[] = [];
  for (const token of tokens) {
    const entry = BY_TOKEN.get(token);
    if (entry && !seen.has(entry.id)) {
      seen.add(entry.id);
      out.push(entry);
      if (out.length >= limit) break;
    }
  }
  return out;
}
