import type { Source } from './types';

/**
 * Every feed here was probed live before being added. Reuters (404), AP (403),
 * the FT and Süddeutsche (paywall stubs returning a single teaser item) were
 * checked and deliberately left out — they cannot supply usable items.
 */
export const SOURCES: Source[] = [
  // ─── Germany ──────────────────────────────────────────────────────────────
  {
    id: 'tagesschau',
    name: 'tagesschau',
    short: 'TAGESSCHAU',
    tier: 1,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://www.tagesschau.de',
    feeds: [
      { url: 'https://www.tagesschau.de/index~rss2.xml', category: 'mixed' },
      { url: 'https://www.tagesschau.de/inland/index~rss2.xml', category: 'politics' },
      { url: 'https://www.tagesschau.de/ausland/index~rss2.xml', category: 'world' },
      { url: 'https://www.tagesschau.de/wirtschaft/index~rss2.xml', category: 'economy' },
      { url: 'https://www.tagesschau.de/wissen/index~rss2.xml', category: 'science' },
    ],
    about: {
      de: 'Nachrichtenangebot von ARD-aktuell, der zentralen Nachrichtenredaktion der ARD. Gilt als wichtigste Nachrichtenquelle Deutschlands.',
      en: 'News service of ARD-aktuell, the central newsroom of Germany’s public broadcaster ARD. Widely regarded as the country’s primary news source.',
    },
    ownership: {
      de: 'ARD — Verbund öffentlich-rechtlicher Landesrundfunkanstalten.',
      en: 'ARD — an association of Germany’s regional public broadcasters.',
    },
    funding: {
      de: 'Rundfunkbeitrag. Keine Werbung im Nachrichtenangebot.',
      en: 'Public broadcasting fee. No advertising in the news service.',
    },
  },
  {
    id: 'dw-de',
    name: 'Deutsche Welle',
    short: 'DW',
    tier: 1,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://www.dw.com/de',
    feeds: [{ url: 'https://rss.dw.com/rdf/rss-de-all', category: 'mixed' }],
    about: {
      de: 'Deutscher Auslandsrundfunk. Berichtet über Deutschland und die Welt, mit starkem internationalem Fokus.',
      en: 'Germany’s international broadcaster, reporting on Germany and the world with a strong international focus.',
    },
    ownership: {
      de: 'Öffentlich-rechtliche Anstalt des Bundes.',
      en: 'Public body established under German federal law.',
    },
    funding: {
      de: 'Steuerfinanziert aus dem Bundeshaushalt.',
      en: 'Funded by the German federal budget through taxation.',
    },
  },
  {
    id: 'zeit',
    name: 'ZEIT ONLINE',
    short: 'ZEIT',
    tier: 1,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://www.zeit.de',
    feeds: [
      { url: 'https://newsfeed.zeit.de/index', category: 'mixed' },
      { url: 'https://newsfeed.zeit.de/politik/index', category: 'politics' },
      { url: 'https://newsfeed.zeit.de/wirtschaft/index', category: 'economy' },
    ],
    about: {
      de: 'Online-Ausgabe der Wochenzeitung DIE ZEIT. Bekannt für lange, einordnende Stücke.',
      en: 'Online edition of the weekly DIE ZEIT, known for long-form, explanatory journalism.',
    },
    ownership: {
      de: 'Zeitverlag Gerd Bucerius, mehrheitlich Dieter von Holtzbrinck Medien.',
      en: 'Zeitverlag Gerd Bucerius, majority-held by Dieter von Holtzbrinck Medien.',
    },
    funding: { de: 'Abonnements und Werbung.', en: 'Subscriptions and advertising.' },
  },
  {
    id: 'spiegel',
    name: 'DER SPIEGEL',
    short: 'SPIEGEL',
    tier: 1,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://www.spiegel.de',
    feeds: [
      { url: 'https://www.spiegel.de/schlagzeilen/tops/index.rss', category: 'mixed' },
      { url: 'https://www.spiegel.de/politik/index.rss', category: 'politics' },
      { url: 'https://www.spiegel.de/wirtschaft/index.rss', category: 'economy' },
      { url: 'https://www.spiegel.de/wissenschaft/index.rss', category: 'science' },
    ],
    about: {
      de: 'Nachrichtenmagazin mit Schwerpunkt auf investigativer Recherche. Betreibt eine eigene Dokumentationsabteilung zur Faktenprüfung.',
      en: 'News magazine known for investigative reporting, with an in-house fact-checking department.',
    },
    ownership: {
      de: 'SPIEGEL-Verlag; Mitarbeiter KG hält einen bedeutenden Anteil.',
      en: 'SPIEGEL-Verlag; an employee partnership holds a significant stake.',
    },
    funding: { de: 'Abonnements, Einzelverkauf und Werbung.', en: 'Subscriptions, newsstand sales and advertising.' },
  },
  {
    id: 'faz',
    name: 'Frankfurter Allgemeine',
    short: 'FAZ',
    tier: 1,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://www.faz.net',
    feeds: [{ url: 'https://www.faz.net/rss/aktuell/', category: 'mixed' }],
    about: {
      de: 'Überregionale Tageszeitung, redaktionell eher liberal-konservativ ausgerichtet. Starker Wirtschaftsteil.',
      en: 'National daily with a broadly liberal-conservative editorial line and a strong business desk.',
    },
    ownership: {
      de: 'FAZIT-Stiftung, eine gemeinnützige Stiftung.',
      en: 'FAZIT-Stiftung, a non-profit foundation.',
    },
    funding: { de: 'Abonnements und Werbung.', en: 'Subscriptions and advertising.' },
  },
  {
    id: 'heise',
    name: 'heise online',
    short: 'HEISE',
    tier: 2,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://www.heise.de',
    feeds: [{ url: 'https://www.heise.de/rss/heise-atom.xml', category: 'technology' }],
    about: {
      de: 'Führendes deutsches IT-Nachrichtenportal. Technisch tief, oft die erste Quelle für Sicherheits- und Netzthemen.',
      en: 'Germany’s leading IT news outlet — technically deep, and often first to report on security and internet policy.',
    },
    ownership: { de: 'Heise Medien GmbH & Co. KG, in Familienbesitz.', en: 'Heise Medien, a family-owned publisher.' },
    funding: { de: 'Werbung, Abonnements und Fachmagazine.', en: 'Advertising, subscriptions and trade magazines.' },
  },
  {
    id: 'netzpolitik',
    name: 'netzpolitik.org',
    short: 'NETZPOLITIK',
    tier: 3,
    region: 'de',
    lang: 'de',
    country: 'DE',
    homepage: 'https://netzpolitik.org',
    feeds: [{ url: 'https://netzpolitik.org/feed/', category: 'technology' }],
    about: {
      de: 'Journalistisches Angebot zu digitalen Grundrechten. Vertritt ausdrücklich eine bürgerrechtliche Position — nützlich, aber keine neutrale Quelle.',
      en: 'Journalism on digital rights. Takes an explicit civil-liberties position — valuable, but not a neutral source.',
    },
    ownership: { de: 'netzpolitik.org e. V., gemeinnütziger Verein.', en: 'netzpolitik.org e. V., a non-profit association.' },
    funding: { de: 'Überwiegend Spenden der Leserinnen und Leser.', en: 'Primarily reader donations.' },
  },

  // ─── Global ───────────────────────────────────────────────────────────────
  {
    id: 'bbc',
    name: 'BBC News',
    short: 'BBC',
    tier: 1,
    region: 'global',
    lang: 'en',
    country: 'UK',
    homepage: 'https://www.bbc.com/news',
    feeds: [
      { url: 'https://feeds.bbci.co.uk/news/world/rss.xml', category: 'world' },
      { url: 'https://feeds.bbci.co.uk/news/technology/rss.xml', category: 'technology' },
      { url: 'https://feeds.bbci.co.uk/news/business/rss.xml', category: 'economy' },
      { url: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', category: 'science' },
    ],
    about: {
      de: 'Öffentlich-rechtlicher Rundfunk des Vereinigten Königreichs mit einem der größten Auslandskorrespondentennetze weltweit.',
      en: 'The UK’s public service broadcaster, with one of the largest foreign correspondent networks in the world.',
    },
    ownership: { de: 'Öffentlich-rechtlich, per Royal Charter.', en: 'Public corporation established by Royal Charter.' },
    funding: { de: 'Rundfunkgebühr im UK; kommerziell finanziert international.', en: 'Licence fee in the UK; commercially funded internationally.' },
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    short: 'GUARDIAN',
    tier: 1,
    region: 'global',
    lang: 'en',
    country: 'UK',
    homepage: 'https://www.theguardian.com',
    feeds: [
      { url: 'https://www.theguardian.com/world/rss', category: 'world' },
      { url: 'https://www.theguardian.com/uk/technology/rss', category: 'technology' },
      { url: 'https://www.theguardian.com/science/rss', category: 'science' },
      { url: 'https://www.theguardian.com/uk/business/rss', category: 'economy' },
    ],
    about: {
      de: 'Britische Tageszeitung mit liberaler bis linksliberaler Ausrichtung und starker investigativer Tradition.',
      en: 'British daily with a liberal to centre-left editorial line and a strong investigative tradition.',
    },
    ownership: {
      de: 'Scott Trust Limited — existiert ausschließlich, um die redaktionelle Unabhängigkeit zu sichern.',
      en: 'Scott Trust Limited, which exists solely to secure the paper’s editorial independence.',
    },
    funding: { de: 'Freiwillige Leserbeiträge und Werbung; keine Paywall.', en: 'Voluntary reader contributions and advertising; no paywall.' },
  },
  {
    id: 'dw-en',
    name: 'DW English',
    short: 'DW EN',
    tier: 1,
    region: 'global',
    lang: 'en',
    country: 'DE',
    homepage: 'https://www.dw.com/en',
    feeds: [{ url: 'https://rss.dw.com/rdf/rss-en-all', category: 'mixed' }],
    about: {
      de: 'Englischsprachiges Angebot der Deutschen Welle — nützlich, um deutsche Themen in internationaler Rahmung zu lesen.',
      en: 'Deutsche Welle’s English service — useful for reading German stories framed for an international audience.',
    },
    ownership: { de: 'Öffentlich-rechtliche Anstalt des Bundes.', en: 'Public body established under German federal law.' },
    funding: { de: 'Steuerfinanziert aus dem Bundeshaushalt.', en: 'Funded by the German federal budget through taxation.' },
  },
  {
    id: 'npr',
    name: 'NPR',
    short: 'NPR',
    tier: 1,
    region: 'global',
    lang: 'en',
    country: 'US',
    homepage: 'https://www.npr.org',
    feeds: [{ url: 'https://feeds.npr.org/1004/rss.xml', category: 'world' }],
    about: {
      de: 'Nicht-kommerzielles US-Hörfunknetzwerk mit ausführlicher Berichterstattung.',
      en: 'Non-commercial American radio network known for in-depth reporting.',
    },
    ownership: { de: 'Non-Profit-Medienorganisation der Mitgliedssender.', en: 'Non-profit media organisation owned by its member stations.' },
    funding: { de: 'Mitgliedsbeiträge, Sponsoring, Stiftungen.', en: 'Member station fees, corporate sponsorship and grants.' },
  },
  {
    id: 'aljazeera',
    name: 'Al Jazeera',
    short: 'AL JAZEERA',
    tier: 2,
    region: 'global',
    lang: 'en',
    country: 'QA',
    homepage: 'https://www.aljazeera.com',
    feeds: [{ url: 'https://www.aljazeera.com/xml/rss/all.xml', category: 'world' }],
    about: {
      de: 'Katarischer Sender mit dichter Berichterstattung aus dem Nahen Osten, Afrika und Asien — Regionen, die westliche Medien oft dünner abdecken. Die staatliche Finanzierung ist bei der Einordnung mitzudenken.',
      en: 'Qatari broadcaster with dense coverage of the Middle East, Africa and Asia — regions Western outlets often cover thinly. Its state funding is worth holding in mind when reading it.',
    },
    ownership: { de: 'Al Jazeera Media Network, finanziert vom Staat Katar.', en: 'Al Jazeera Media Network, funded by the state of Qatar.' },
    funding: { de: 'Staatliche Mittel Katars.', en: 'Funding from the Qatari state.' },
  },
  {
    id: 'euronews',
    name: 'Euronews',
    short: 'EURONEWS',
    tier: 2,
    region: 'global',
    lang: 'en',
    country: 'EU',
    homepage: 'https://www.euronews.com',
    feeds: [{ url: 'https://www.euronews.com/rss?level=theme&name=news', category: 'world' }],
    about: {
      de: 'Paneuropäischer Nachrichtensender mit Fokus auf EU-Politik und europäische Themen.',
      en: 'Pan-European news channel focused on EU policy and European affairs.',
    },
    ownership: { de: 'Mehrheitlich Alpac Capital.', en: 'Majority-owned by Alpac Capital.' },
    funding: { de: 'Werbung und EU-Fördermittel für bestimmte Programme.', en: 'Advertising and EU funding for specific programming.' },
  },
  {
    id: 'economist',
    name: 'The Economist',
    short: 'ECONOMIST',
    tier: 1,
    region: 'global',
    lang: 'en',
    country: 'UK',
    homepage: 'https://www.economist.com',
    feeds: [{ url: 'https://www.economist.com/finance-and-economics/rss.xml', category: 'economy' }],
    about: {
      de: 'Wochenzeitung zu Wirtschaft und Weltpolitik. Vertritt offen eine wirtschaftsliberale Linie.',
      en: 'Weekly on economics and world affairs, with an openly classical-liberal editorial stance.',
    },
    ownership: { de: 'The Economist Group; Exor hält den größten Anteil.', en: 'The Economist Group; Exor holds the largest stake.' },
    funding: { de: 'Abonnements und Werbung.', en: 'Subscriptions and advertising.' },
  },
  {
    id: 'arstechnica',
    name: 'Ars Technica',
    short: 'ARS',
    tier: 2,
    region: 'global',
    lang: 'en',
    country: 'US',
    homepage: 'https://arstechnica.com',
    feeds: [{ url: 'https://feeds.arstechnica.com/arstechnica/index', category: 'technology' }],
    about: {
      de: 'Technikpublikation mit ungewöhnlich tiefer technischer Analyse.',
      en: 'Technology publication known for unusually deep technical analysis.',
    },
    ownership: { de: 'Condé Nast.', en: 'Condé Nast.' },
    funding: { de: 'Werbung und Abonnements.', en: 'Advertising and subscriptions.' },
  },
  {
    id: 'nature',
    name: 'Nature',
    short: 'NATURE',
    tier: 1,
    region: 'global',
    lang: 'en',
    country: 'UK',
    homepage: 'https://www.nature.com',
    feeds: [{ url: 'https://www.nature.com/nature.rss', category: 'science' }],
    about: {
      de: 'Eine der angesehensten wissenschaftlichen Fachzeitschriften. Beiträge durchlaufen ein Peer-Review-Verfahren.',
      en: 'One of the most respected scientific journals; research papers go through peer review.',
    },
    ownership: { de: 'Springer Nature.', en: 'Springer Nature.' },
    funding: { de: 'Abonnements, Publikationsgebühren.', en: 'Subscriptions and article processing charges.' },
  },
  {
    id: 'sciencedaily',
    name: 'ScienceDaily',
    short: 'SCIENCEDAILY',
    tier: 2,
    region: 'global',
    lang: 'en',
    country: 'US',
    homepage: 'https://www.sciencedaily.com',
    feeds: [{ url: 'https://www.sciencedaily.com/rss/top/science.xml', category: 'science' }],
    about: {
      de: 'Aggregiert Pressemitteilungen von Forschungseinrichtungen. Praktisch für den Überblick — die Texte stammen aber von den Institutionen selbst, nicht von unabhängigen Redakteuren.',
      en: 'Aggregates press releases from research institutions. Useful for breadth, but the text comes from the institutions themselves rather than independent reporters.',
    },
    ownership: { de: 'ScienceDaily LLC.', en: 'ScienceDaily LLC.' },
    funding: { de: 'Werbung.', en: 'Advertising.' },
  },
];

export const SOURCE_BY_ID = new Map(SOURCES.map((s) => [s.id, s]));

export function getSource(id: string): Source | undefined {
  return SOURCE_BY_ID.get(id);
}
